### ISSUE TITLE
Class SurfacePositionV2Msg wrong byte casting in getHorizontalContainmentRadiusLimit()

### ISSUE THREAD

**Issue by lvalkenbergECTRL** [SeRoSystems/lib1090#23]
In the class SurfacePositionV2Msg line 84 there is a byte casting in the return statement: 

`case 7:
				return (byte) (hasNICSupplementA() ? 75 : 185.2);`

Because of this, if NIC A if false the return value will be -71 instead of 185.2

**Comment by fixje** [comment]
fixed in 36546140180bff667fe8835768f5599f2245c271 which is now released with v4.1.1
